### PR TITLE
make eig faster by using sarrays own eig

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Faster than this?

``` jl
julia> using ContMechTensors, Benchmarktools

julia> A = rand(SymmetricTensor{2,3});

julia> Base.@pure function pureeig{dim, T, M}(S::SymmetricTensor{2, dim, T, M})
           S_m = Symmetric(Array(S))
           λ, ϕ = eig(S_m)
           Λ = Tensor{1, dim}(λ)
           Φ = Tensor{2, dim}(ϕ)
           return Λ, Φ
       end
pureeig (generic function with 1 method)

julia> @benchmark eig($A)
BenchmarkTools.Trial: 
  samples:          10000
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  2.89 kb
  allocs estimate:  25
  minimum time:     11.248 μs (0.00% GC)
  median time:      12.748 μs (0.00% GC)
  mean time:        13.230 μs (1.11% GC)
  maximum time:     1.511 ms (97.17% GC)

julia> @benchmark pureeig($A)
BenchmarkTools.Trial: 
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  0.00 bytes
  allocs estimate:  0
  minimum time:     1.813 ns (0.00% GC)
  median time:      1.823 ns (0.00% GC)
  mean time:        1.831 ns (0.00% GC)
  maximum time:     4.835 ns (0.00% GC)
```

**Comment by fredrikekre** [comment]
Sign on eigenvectors...

**Comment by KristofferC** [comment]
That's just a convention?

**Comment by KristofferC** [comment]
Also, that is a very non pure function, at least how Julia defines it.

**Comment by fredrikekre** [comment]
Yea, well it failed on the signs. WIll it always return the same sign?

**Comment by fredrikekre** [comment]
But it is much faster :p

**Comment by KristofferC** [comment]
Oh..

**Comment by KristofferC** [comment]
The signs are correct for my computer... Maybe it is different version of StaticArrays on travis and my computer?

**Comment by fredrikekre** [comment]
It could be random from time to time, couldn't it?

**Comment by KristofferC** [comment]
The algorithm used should be deterministic.

**Comment by fredrikekre** [comment]
Try using the tagged version of StaticArrays on your local pc? will it change the sign?

**Comment by KristofferC** [comment]
Yep, v0.1.0 is for StaticArrays is in a  METADATA PR so lets just wait until it is tagged and rerun the tests.

**Pull request merged**
