### PR TITLE
change the way docs are ran

### PR DESCRIPTION
**Pull request by KristofferC**
Lets try this then

### CODE REVIEW

**Comment by fredrikekre** [comment]
seems to work

**Comment by KristofferC** [comment]
Build is failing though.. https://travis-ci.org/KristofferC/ContMechTensors.jl/jobs/173855954

**Comment by fredrikekre** [comment]
Just a travis timeout?

**Comment by KristofferC** [comment]
Yeah but why wasnt it marked as finished? This only happened on the one that the docs are run on.

**Comment by fredrikekre** [comment]
Hmmm... `Pkg.test` passes like normal locally

**Pull request merged**
