### PR TITLE
type stability

### LINKED ISSUE #56: Performance weirdness
Taken from https://gist.github.com/KristofferC/44854cc1c962ab81bfb5b5ffaa3d7edd

Float64 -> Float32 = 1000 times slower with Float32 for symmetric.

```jl
["other","ContMechTensors.symmetric - dim 2 - order 4 - Float32"]	1.671 μs (5%)	0.000 ns	960.00 bytes (1%)	48
["other","ContMechTensors.symmetric - dim 2 - order 4 - Float64"]	3.931 ns (5%)	0.000 ns	0.00 bytes (1%)	0
```

Similar here:

```jl
["other","ContMechTensors.skew - dim 3 - order 2 - Float32"]	28.352 ns (5%)	0.000 ns	128.00 bytes (1%)	2
["other","ContMechTensors.skew - dim 3 - order 2 - Float64"]	4.135 ns (5%)	0.000 ns	0.00 bytes (1%)	0
```

### PR DESCRIPTION
**Pull request by fredrikekre**
Fix #56 

https://gist.github.com/fredrikekre/2936b88a9190e1b7f4d08acfc8a426b8

### CODE REVIEW

**Comment by fredrikekre** [comment]
Perhaps this is removed with #60 but w/e

**Comment by KristofferC** [comment]
I fixed these in #60 by just dividing. Maybe your way is faster.

**Comment by fredrikekre** [comment]
Probably the same. Well, I guess your way needs to promote the `Int` you divide with to a `T` every time though.

**Comment by fredrikekre** [comment]
Included in #60

**Pull request closed without merging**
