### PR TITLE
Try to fix doctests by adding ForwardDiff to REQUIRE in test folder

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Ahh thats why!

**Comment by KristofferC** [comment]
Crap, `INFO: Removing ForwardDiff v0.2.5`. It does that before the success is ran.

**Comment by fredrikekre** [comment]
There is not way to add require for docs then? eg. `docs/REQUIRE`

**Comment by fredrikekre** [comment]
maybe just add `Pkg.add("ForwardDiff"); using ForwardDiff` at the top of `make.jl`?

**Pull request merged**
