### PR TITLE
Change deprecated syntax

### PR DESCRIPTION
**Pull request by fredrikekre**
Realized now that this wont work on 0.4 so tests will break. Merge when 0.5 is released and scrap 0.4 support since it is slow on 0.4 anyway?

### CODE REVIEW

**Comment by KristofferC** [comment]
Adding `@compat` before the functions should make it work on 0.4 if we care...

**Comment by fredrikekre** [comment]
Yea sure, I can add that.

**Comment by fredrikekre** [comment]
Oh, and also on 0.4:

``` jl
# First run
julia> tic(); include("test/runtests.jl"); toc()
elapsed time: 35.148767401 seconds

# Second run
julia> tic(); include("test/runtests.jl"); toc()
elapsed time: 1.340915988 seconds
```

while on 0.5:

``` jl
# First run
julia> tic(); include("test/runtests.jl"); toc()
elapsed time: 145.967444178 seconds

# Second run
julia> tic(); include("test/runtests.jl"); toc()
elapsed time: 17.92940773 seconds
```

**Comment by KristofferC** [comment]
I wonder why the second run is so slow... Should check that stuff didn't become slower in general due to some julia bug.

**Comment by fredrikekre** [comment]
But it is sooo much **slower on 0.5**?!

**Comment by KristofferC** [comment]
I profiled. The time is spent in type inference. Hm.

**Comment by KristofferC** [comment]
Hah, removing the `@testset` and changing `@test` to @assert makes the second run take 2.2 seconds on 0.5

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/18077

**Pull request merged**
