### PR TITLE
Add test and fix another bug

### PR DESCRIPTION
**Pull request by fredrikekre**
Fixes `tdot(::SymmetricTensor{2,dim})`

Also adds tests for this and for #22

### CODE REVIEW

**Comment by KristofferC** [comment]
thx

**Comment by fredrikekre** [comment]
meh... another error...

`tdot(S1::SymmetricTensor)` does not return a symmetric tensor the way that `tdot(S1::Tensor)` does.

 (https://github.com/KristofferC/ContMechTensors.jl/blob/master/src/tensor_ops.jl#L134)

Which is better:

``` jl
@inline tdot{dim}(S1::SymmetricTensor{2,dim}) = convert(SymmetricTensor{2,dim}, dot(S1,S1))
```

or 

``` jl
@inline tdot{dim}(S1::SymmetricTensor{2,dim}) = tdot(convert(Tensor{2,dim}, S1))
```

**Comment by KristofferC** [comment]
The latter.

**Comment by fredrikekre** [comment]
Should it be parametrized by type then as well?

``` jl
@inline tdot{dim}(S1::SymmetricTensor{2,dim,T}) = tdot(convert(Tensor{2,dim,T}, S1))
```

**Comment by KristofferC** [comment]
Nope, not needed.

**Pull request merged**
