### PR TITLE
fix one for fourth order tensors

### LINKED ISSUE #79: one for fourth order symmetric tensor
```jl
julia> v = rand(Tensor{4,3});

julia> I = one(Tensor{4,3});

julia> I ⊡ v - v
3×3 ContMechTensors.Tensor{2,3,Float64,9}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> v = rand(SymmetricTensor{2,3});

julia> I = one(SymmetricTensor{4,3});

julia> I ⊡ v - v
3×3 ContMechTensors.SymmetricTensor{2,3,Float64,6}:
 0.0      0.14482   0.79655 
 0.14482  0.0       0.470157
 0.79655  0.470157  0.0  
```

### PR DESCRIPTION
**Pull request by fredrikekre**
Fix #79 

Also removed `diagm` for fourth order tensors, since it is not that clear what the diagonal is.

### CODE REVIEW

**Comment by KristofferC** [comment]
Cool. Thanks for fixing this.

**Comment by fredrikekre** [comment]
I guess `one` could be a `@pure` function?

**Comment by KristofferC** [comment]
No, I don't think so. AFAIU it should only be used for extremely simple functions that compute a type or an integer etc.

**Comment by fredrikekre** [comment]
Now this holds too, which makes sense:
```jl
julia> II = one(Tensor{4,3}); IIs = one(SymmetricTensor{4,3});

julia> symmetric(II) ≈ IIs
true
```

on master:
```jl
julia> II = one(Tensor{4,3}); IIs = one(SymmetricTensor{4,3});

julia> symmetric(II) ≈ IIs
false
```

**Pull request merged**
