### PR TITLE
[WIP] Fixes for Julia 0.6

### LINKED ISSUE #103: Make working on 0.6
think most problems are upstream though

### PR DESCRIPTION
**Pull request by fredrikekre**
close #103

### CODE REVIEW

**Comment by KristofferC** [comment]
lets check nightly again

**Comment by fredrikekre** [comment]
We need to add some `Compat` stuff. With the first commit here it will go through deprecation warning every call on 0.5

**Comment by KristofferC** [comment]
Will it?

**Comment by fredrikekre** [comment]
Yes, but we are not using deprecated functions so my bad :) Using deprecated functions go through a lookup somehow so that the deprecation warning is only printed once.

But it doesn't apply here, since `sum(abs2, x)` is equally fast on 0.5 and 0.6.

**Comment by fredrikekre** [comment]
StaticArrays works now on master.

- [ ] Should we remove [dot-operations](https://github.com/KristofferC/ContMechTensors.jl/blob/master/src/ContMechTensors.jl#L159)? That give deprecation warning now.
- [ ] On `v0.6` [this](https://github.com/KristofferC/ContMechTensors.jl/blob/master/src/ContMechTensors.jl#L205) method is more specific than [this](https://github.com/KristofferC/ContMechTensors.jl/blob/master/src/ContMechTensors.jl#L183), how come? That causes some test to fail too:

```julia
julia> ones(Vec{3})
ERROR: ArgumentError: `one` only defined for order 2 and 4
Stacktrace:
 [1] one(...) at /home/fredrik/Dropbox/Programming/ContMechTensors.jl/src/ContMechTensors.jl:237
 [2] ones(::Type{ContMechTensors.Tensor{1,3,T,3} where T}) at /home/fredrik/Dropbox/Programming/ContMechTensors.jl/src/ContMechTensors.jl:190
```

**Comment by fredrikekre** [comment]
tbc in https://github.com/KristofferC/Tensors.jl/pull/2

**Pull request closed without merging**
