### PR TITLE
move out tests into separate file

### PR DESCRIPTION
**Pull request by KristofferC**
split tests in runtests.jl file into a separate one.

### CODE REVIEW

**Comment by KristofferC** [comment]
Looks like StaticArrays updated and the signs for eigenvectors changed again.. zz.

**Comment by fredrikekre** [comment]
Perhaps we can do some hack like [this](https://github.com/KristofferC/ContMechTensors.jl/blob/kc/test_split/test/test_misc.jl#L320) but I cannot think of a good way of doing that in the docstring...

**Comment by KristofferC** [comment]
https://travis-ci.org/KristofferC/ContMechTensors.jl/jobs/181885905

wut...

**Comment by fredrikekre** [comment]
#84 ? But tests passed before we merged that one.

**Comment by fredrikekre** [comment]
https://github.com/KristofferC/ContMechTensors.jl/blob/b53ecf7e6848e605c63c2166850632563476b758/test/test_misc.jl#L177

this should be `for i in 1:dim, j in i:dim` to be consistent with looping over upper triangle. But the `compute_index` should just flip the indices so it shouldn't matter...

The weird thing is that tests passes on master still.

**Comment by fredrikekre** [comment]
No, wait, `tensor_create` calls on `f` with the upper triangle, so we need to have the same in the test loop since our test functions are not symmetric.

Still weird that it passes on master, or at least goes by silently.

**Comment by fredrikekre** [comment]
It passes on this branch if we update that loop, which should be correct. Question is why it passes on master :p

**Comment by fredrikekre** [comment]
Hmm, it is the correct looping on master :p You must have started with an outdated testfile?

diff between my copy-paste and yours:

```diff
fredrik@fredrik-laptop:~/Dropbox/Programming/ContMechTensors.jl$ git diff fe/test kc/test_split 
diff --git a/test/test_misc.jl b/test/test_misc.jl
index 52ff0c9..0bd8a1d 100644
--- a/test/test_misc.jl
+++ b/test/test_misc.jl
@@ -174,9 +174,9 @@ for T in (Float32, Float64)
             end
         end
 
-        for i in 1:dim, j in i:dim
+        for i in 1:dim, j in 1:i
             @test Af_sym[i,j] == T(fij(i, j))
-            for k in 1:dim, l in k:dim
+            for k in 1:dim, l in 1:k
                  @test AAf_sym[i,j,k,l] == T(fijkl(i,j,k,l))
             end
         end

```

**Comment by KristofferC** [comment]
That's what I asked if you also copied :P Ok, will fix.

**Comment by fredrikekre** [comment]
I was sure I did :p

**Pull request merged**
