### PR TITLE
Restructure code

### LINKED ISSUE #59: Restructure code
I would like to restructure the code. Currently it is quite messy.
I propose the following structure:

* `tensor_products.jl`: `dcontract`, `dot`, `tdot`, `otimes` and perhaps `cross`
* `nice_name.jl`: operations like `symmetric`, `transpose` etc. which permutes the input tensor. Name suggestion for file name?
* `other_operations.jl`: other operations, like `inv`, `det`, `trace`, `norm`
* `continuum_mech.jl`: `dev`, `mean`, `skew` ...
* `special_ops.jl`: specialized weird operations like `dotdot` etc.

Thoughts?

### PR DESCRIPTION
**Pull request by fredrikekre**
Fix #59

Better structure?
Less confusing with the specialised symmetric ops next to the non-symmetric ops too imo.

* `tensor_products.jl`: `dcontract`, `dot`, `tdot`, `otimes`, `cross`
* `transpose_symmetric.jl`: `transpose`, `symmetric`, `skew`, `issymmetric`
* `math_ops.jl`: `norm`, `det`, `inv`, `eig`, `trace`, `dev`
* `special_ops.jl`: `dotdot`

### CODE REVIEW

**Comment by KristofferC** [comment]
Performance tag? `transpose_symmetric` sounds a bit weird but otherwise good.

**Comment by fredrikekre** [comment]
I am open for name suggestions. Couldn't come up with something better...

**Comment by fredrikekre** [comment]
We could perhaps split it in two files. `transpose.jl` and `symmetry.jl` or soemthing

**Comment by fredrikekre** [comment]
Two times in a row that nightly on linux times out.

**Comment by KristofferC** [comment]
Yes. There is an issue on Documenter.jl about it.

**Comment by KristofferC** [comment]
If this is just moving code around, good to go from my pov.

**Comment by fredrikekre** [comment]
Yes, all copy paste.

**Pull request merged**
